name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
env:
  DOTNET_VERSION: 6.0.x

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '11'
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Begin Sonar scan
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet sonarscanner begin /o:vianneydoleans /k:VianneyDoleans_MyBlogAPI-NET-Core /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io /d:sonar.cs.vstest.reportsPaths=**/TestResults/*.trx /d:sonar.cs.opencover.reportsPaths=**/TestResults/*/coverage.opencover.xml
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover
    - name: End Sonar scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
